language: python
python:
  - "3.6"
install:
  - pip install pytest pytest-cov
  - pip install codecov
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - pytest tests --cov=./ --cov-report term-missing
after_success:
  - codecov